### ISSUE TITLE
Chest Anywhere

### ISSUE THREAD

**Issue by khanshoaib3** [khanshoaib3/stardew-access#127]
Chest Anywhere mod issue:-
```
[Chests Anywhere] Mod failed handling that command:
IndexOutOfRangeException: Index was outside the bounds of the array.
   at Pathoschild.Stardew.ChestsAnywhere.ModEntry.RunCommand(String command, String[] args) in D:\modding\Stardew Valley\Github\Pathoschild_StardewMods\ChestsAnywhere\ModEntry.cs:line 78
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate) in SMAPI\Framework\SCore.cs:line 662
cam help
[Chests Anywhere] Mod failed handling that command:
IndexOutOfRangeException: Index was outside the bounds of the array.
   at Pathoschild.Stardew.ChestsAnywhere.ModEntry.RunCommand(String command, String[] args) in D:\modding\Stardew Valley\Github\Pathoschild_StardewMods\ChestsAnywhere\ModEntry.cs:line 78
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate) in SMAPI\Framework\SCore.cs:line 662
```

**Comment by khanshoaib3** [comment]
### What works

The main functionality which is accessing multiple chests from multiple locations works. We can use the mod's keybindings to change the selected chest and category, [here's the controls](https://github.com/Pathoschild/StardewMods/tree/stable/ChestsAnywhere#configjson)

### What doesn't work or what I'll try to fix

- Right now, it doesn't speak the chest's or location name it just changed to.
- SV access also does not acknowledges the custom chest names.
- The overlay that let's us customize the chest info isn't accessible.
